name: Deploy app to gh-pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  shinylive:
    uses: posit-dev/r-shinylive/.github/workflows/deploy-app.yaml@actions-v1
    permissions:
      pages: write
      id-token: write